# 01-01 : Training Data

Load the Kleister NDA dataset to get a better understanding of the data.

In [1]:
import pandas as pd

## 1. Configuration

In [2]:
data_path = '../../../data'
raw_data_path = f'{data_path}/raw'
input_path = f'{raw_data_path}/kleister-nda'

header_file = f'{input_path}/in-header.tsv'
train_file = f'{input_path}/train/in.tsv.xz'
expected_file = f'{input_path}/train/expected.tsv'
expected_original_file = f'{input_path}/train/expected-original.tsv'

## 2. Load Data

### 2.1 Header File

In [3]:
# read tab separated file with pandas
header = list(pd.read_csv(header_file, sep='\t').columns)
print(header)

['filename', 'keys', 'text_djvu', 'text_tesseract', 'text_textract', 'text_best']

### 2.2 Train Data

In [4]:
# read tge in.tsv.xz file with pandas
df_train = pd.read_csv(train_file, sep='\t', compression='xz', header=None, names=header)

# show the data shape
display(df_train)
print('Shape:', df_train.shape)

,filename,keys,text_djvu,text_tesseract,text_textract,text_best
0,00a1d238e37ac225b8045a97953e845d.pdf,effective_date jurisdiction party term,EX-10.23 5 dex1023.htm COVENANT NOT TO COMPETE...,EX-10.23 5 dex1023.htm COVENANT NOT TO COMPETE...,EX-10.23 5 dlex1023.htm COVENANT NOT TO COMPET...,EX-10.23 5 dex1023.htm COVENANT NOT TO COMPETE...
1,031470434423a8c40105a4b404ced88b.pdf,effective_date jurisdiction party term,EX-99.(E)(2) 3 d450961dex99e2.htm EX-(E)(2)\nE...,EX-99.(E)(2) 3 d450961dex99e2.htm EX-(E)(2) »L...,EX-99.(E)(2) 3 d450961dex99e2.htm EX-(E)(2)\nE...,EX-99.(E)(2) 3 d450961dex99e2.htm EX-(E)(2)\nE...
2,03ae3b511276b560dc8806eb61b9d063.pdf,effective_date jurisdiction party term,EX-10.3 6 d281487dex103.htm CONFIDENTIALITY AN...,EX-10.3 6 d281487dex103.htm CONFIDENTIALITY AN...,EX-10.3 6 d281487dex103.htm CONFIDENTIALITY AN...,EX-10.3 6 d281487dex103.htm CONFIDENTIALITY AN...
3,03efbda01358533c167ca9b1e6d72051.pdf,effective_date jurisdiction party term,EX-10.26 26 ex10-26.txt NON-CIRCUMVENTION AND ...,EX-10.26 26 ex10-26.txt NON-CIRCUMVENTION AND ...,EX-10.26 26 x10-26.txt NON-CIRCUMVENTION AND N...,EX-10.26 26 ex10-26.txt NON-CIRCUMVENTION AND ...
4,03fd0e629b617da00c54794a8a78b24d.pdf,effective_date jurisdiction party term,EX-7.5 2 dex75.htm AMENDED AND RESTATED CONFID...,EX-7.5 2 dex75.htm AMENDED AND RESTATED CONFID...,EX-7.5 2 dex75.htm AMENDED AND RESTATED CONFID...,EX-7.5 2 dex75.htm AMENDED AND RESTATED CONFID...
...,...,...,...,...,...,...
249,fbf608b62ef498171b70fb7b36be61a0.pdf,effective_date jurisdiction party term,"EX-10.3 6 dex103.htm NON COMPETITION, NON SOLI...","EX-10.3 6 dex103.htm NON COMPETITION, NON SOLI...","EX-10.3 6 dex103.htm NON COMPETITION, NON SOLI...","EX-10.3 6 dex103.htm NON COMPETITION, NON SOLI..."
250,fc2ce0e2abdcf676a1d4ab95191a9d17.pdf,effective_date jurisdiction party term,EX-2.4 5 dex24.htm NON-COMPETITION AND CONFIDE...,EX-2.4 5 dex24.htm NON-COMPETITION AND CONFIDE...,EX-2.4 5 dex24.htm NON-COMPETITION AND CONFIDE...,EX-2.4 5 dex24.htm NON-COMPETITION AND CONFIDE...
251,fc34f2d7a61e531870d05910c5c3599b.pdf,effective_date jurisdiction party term,EX-10.37 15 d255425dex1037.htm EMPLOYEE NON-DI...,EX-10.37 15 d255425dex1037.htm EMPLOYEE NON-DI...,EX-10.37 15 d255425dex1037.hti EMPLOYEE NON-DI...,EX-10.37 15 d255425dex1037.htm EMPLOYEE NON-DI...
252,fdf657ad612664d6f363040992f9a93c.pdf,effective_date jurisdiction party term,EX-7.2 3 dex72.htm CONFIDENTIALITY AGREEMENT\n...,EX-7.2 3 dex72.htm CONFIDENTIALITY AGREEMENT\n...,EX-7.2 3 dex72.htm CONFIDENTIALITY AGREEMENT\n...,EX-7.2 3 dex72.htm CONFIDENTIALITY AGREEMENT\n...
253,ff2f9c3d7198b961852b39b2b3969255.pdf,effective_date jurisdiction party term,EX-10.1 2 dex101.htm INDEMNIFICATION AGREEMENT...,EX-10.1 2 dex101.htm INDEMNIFICATION AGREEMENT...,EX-10.1 2 dex101.htm INDEMNIFICATION AGREEMENT...,EX-10.1 2 dex101.htm INDEMNIFICATION AGREEMENT...

Shape: (254, 6)

### 2.3 Expected Values

In [5]:
df_expected = pd.read_csv(expected_file, sep='\t', header=None, names=['expected'])

display(df_expected)
print('Shape:', df_expected.shape)

                                              expected
0    effective_date=2001-04-18 jurisdiction=Oregon ...
1    effective_date=2017-02-10 jurisdiction=Califor...
2    effective_date=2012-01-06 jurisdiction=Florida...
3    effective_date=1999-02-08 jurisdiction=Pennsyl...
4    effective_date=2011-07-13 jurisdiction=Califor...
..                                                 ...
249  effective_date=2005-03-28 jurisdiction=Florida...
250  effective_date=2006-04-13 jurisdiction=New_Yor...
251  effective_date=2010-03-19 jurisdiction=Delawar...
252  effective_date=2011-01-27 jurisdiction=Califor...
253  jurisdiction=Delaware party=Lydall_Inc. party=...

[254 rows x 1 columns]

Shape: (254, 1)

In [6]:
df_expected_original = pd.read_csv(expected_original_file, sep='\t', header=None, names=['expected'])

display(df_expected_original)
print('Shape:', df_expected_original.shape)

                                              expected
0    effective_date=2001-04-18 jurisdiction=Oregon ...
1    effective_date=2017-02-10 jurisdiction=Califor...
2    effective_date=2012-01-06 jurisdiction=Florida...
3    effective_date=1999-02-08 jurisdiction=Pennsyl...
4    effective_date=2011-07-13 jurisdiction=Califor...
..                                                 ...
249  effective_date=2005-03-28 jurisdiction=Florida...
250  effective_date=2006-04-13 jurisdiction=New_Yor...
251  effective_date=2010-03-19 jurisdiction=Delawar...
252  effective_date=2011-01-27 jurisdiction=Califor...
253  jurisdiction=Delaware party=Lydall_Inc. party=...

[254 rows x 1 columns]

Shape: (254, 1)

## 3. Preprocessing

### 3.1 Expected Values to Dictionary

The expected values for each row are in the following string format:

`effective_date=2007-01-03 jurisdiction=New_York party=Potomac_Key_Group_LLC party=Compudyne_Corporation term=2_years`

In [7]:
# convert the string to a dictionary
def convert_to_dict(s):
    d = {}
    for item in s.split(' '):
        key, value = item.split('=')
        d[key] = value
    return d

# convert the expected values to a list of dictionaries
df_expected['dict'] = df_expected['expected'].apply(lambda x: convert_to_dict(x))
# show the first 5 rows
display(df_expected.head())
print('Shape:', df_expected.shape)

,expected,dict
0,effective_date=2001-04-18 jurisdiction=Oregon ...,"{'effective_date': '2001-04-18', 'jurisdiction..."
1,effective_date=2017-02-10 jurisdiction=Califor...,"{'effective_date': '2017-02-10', 'jurisdiction..."
2,effective_date=2012-01-06 jurisdiction=Florida...,"{'effective_date': '2012-01-06', 'jurisdiction..."
3,effective_date=1999-02-08 jurisdiction=Pennsyl...,"{'effective_date': '1999-02-08', 'jurisdiction..."
4,effective_date=2011-07-13 jurisdiction=Califor...,"{'effective_date': '2011-07-13', 'jurisdiction..."

Shape: (254, 2)