# 02-01 : Read all the Kleister NDA Data

In [33]:
from typing import Any, Dict, List

import pandas as pd

## 1. Configuration

In [34]:
data_path = '../../../data'
raw_data_path = f'{data_path}/raw'
input_path = f'{raw_data_path}/kleister-nda'
header_file = f'{input_path}/in-header.tsv'

## 2. Load Data

### 2.1 Functions

#### 2.1.1 Read Input Data

In [35]:
def read_input(set_name:str,
               input_path:str,
               headers:List[str],
               keys_column:str='keys') -> pd.DataFrame:
    """
    Read the compressed input file and return a DataFrame.
    
    Parameters
    ----------
    set_name : str
        The name of the dataset [dev-0, test-A, train].
    input_path : str
        The path to the input file.
    headers : List[str]
        The list of headers to be used for the DataFrame.
    keys_column : str
        The name of the column containing keys. Default is 'keys'.
        
    Returns
    -------
    pd.DataFrame
        A DataFrame containing the data from the input file.
    """
    # read the input file
    df_data = pd.read_csv(
        f'{input_path}/{set_name}/in.tsv.xz',
        sep='\t',
        header=None,
        names=headers,
        quoting=3,
        encoding='utf-8'
    )
    
    # convert the keys column to a list
    df_data[f"{keys_column}_list"] = df_data[keys_column].str.split(' ')
    
    # return the data
    return df_data
    
## test the function
df_dev = read_input('dev-0', input_path, ['filename', 'keys', 'text_djvu', 'text_tesseract', 'text_textract', 'text_best'])
display(df_dev)

keys_list = df_dev.iloc[0].keys_list
print(f"Keys list: {keys_list}")

,filename,keys,text_djvu,text_tesseract,text_textract,text_best,keys_list
0,073f3b9eb0c7088be4ef688f4edfdb6d.pdf,effective_date jurisdiction party term,EX-10 5 ex10-4 .htm EXHIBIT 10.4\nExhibit 10.4...,EX-10 5 ex10-4.htm EXHIBIT 10.4\nExhibit 10.4\...,EX-10 ex10-4.htm EXHIBIT 10.4\nExhibit 10.4\nA...,EX-10 5 ex10-4 .htm EXHIBIT 10.4\nExhibit 10.4...,"[effective_date, jurisdiction, party, term]"
1,0d3f3a02773949e285cfc3ad2fe4dbf5.pdf,effective_date jurisdiction party term,Exhibit L-2\nto Amended and Restated Loan Guar...,Exhibit I.-2\nto Amended and Restated Loan Gua...,Exhibit L-2\nto Amended and Restated Loan Guar...,Exhibit L-2\nto Amended and Restated Loan Guar...,"[effective_date, jurisdiction, party, term]"
2,0f32a3a54d9c1e42d26f66746821c3bf.pdf,effective_date jurisdiction party term,EX-99.D.3 12 d438799dex99d3.htm AMENDED AND RE...,EX-99.D.3 12 d438799dex99d3.htm AMENDED AND RE...,EX-99.D.3 12 d438799dex99d3.htm AMENDED AND RE...,EX-99.D.3 12 d438799dex99d3.htm AMENDED AND RE...,"[effective_date, jurisdiction, party, term]"
3,0fe8eaee697774ac95f9186dd2fc3364.pdf,effective_date jurisdiction party term,EX-10.1 2 a09-6413_1ex10d1.htm EX-10.1\nExhibi...,EX-10.1 2 a09-6413_1ex10d1.htm EX-10.1\nExhibi...,EX-10.1 2 a09-6413_1ex10d1.htm EX-10.1\nExhibi...,EX-10.1 2 a09-6413_1ex10d1.htm EX-10.1\nExhibi...,"[effective_date, jurisdiction, party, term]"
4,11d0a5b1f6e460c7033d57661026d00c.pdf,effective_date jurisdiction party term,EX-99.(D)(3) 8 d901048dex99d3.htm CONFIDENTIAL...,EX-99.(D)(3) 8 d901048dex99d3.htm CONFIDENTIAL...,EX-99.(D)(3) 8 d901048dex99d3.htm CONFIDENTIAL...,EX-99.(D)(3) 8 d901048dex99d3.htm CONFIDENTIAL...,"[effective_date, jurisdiction, party, term]"
...,...,...,...,...,...,...,...
78,e90afd0c36ad8ce86d62ef0cbe75cde3.pdf,effective_date jurisdiction party term,EX-99.D.3 9 d70867dex99d3.htm CONFIDENTIALITY ...,EX-99.D.3 9 d70867dex99d3.htm CONFIDENTIALITY ...,EX-99.D.3 9 d70867dex99d3.htm CONFIDENTIALITY ...,EX-99.D.3 9 d70867dex99d3.htm CONFIDENTIALITY ...,"[effective_date, jurisdiction, party, term]"
79,ead4ae70800732aeb59f689dc2e60117.pdf,effective_date jurisdiction party term,Exhibit D\nNon-Disclosure Agreement\nMicrosoft...,Exhibit D\nNon-Disclosure Agreement\nMicrosoft...,Exhibit D\nNon-Disclosure Agreement\nMicrosoft...,Exhibit D\nNon-Disclosure Agreement\nMicrosoft...,"[effective_date, jurisdiction, party, term]"
80,f28c4f3d35a152dd415f9b255122cb38.pdf,effective_date jurisdiction party term,EX-99.(E)(2) 3 dex99e2.htm CONFIDENTIALITY AGR...,EX-99.(E)(2) 3 dex99e2.htm CONFIDENTIALITY AGR...,X-99.(E)(2) 3 dex99e2.htm CONFIDENTIALITY AGRE...,EX-99.(E)(2) 3 dex99e2.htm CONFIDENTIALITY AGR...,"[effective_date, jurisdiction, party, term]"
81,f4c39490e63ee60b91f354c6b00a413b.pdf,effective_date jurisdiction party term,EX-99.(D)(3) 10 d802321dex99d3.htm EX-99.(D)(3...,EX-99.(D)(3) 10 d802321dex99d3.htm EX-99.(D)(3...,EX-99.(D)(3) 10 d802321dex99d3.htm EX-99.(D)(3...,EX-99.(D)(3) 10 d802321dex99d3.htm EX-99.(D)(3...,"[effective_date, jurisdiction, party, term]"
82,f5767a1bcfba57c7f5d07b9404a9ac3a.pdf,effective_date jurisdiction party term,EX-10.58 4 d13265dex1058.htm EX-10.58\nExhibit...,EX-10.58 4 d13265dex1058.htm EX-10.58\nExhibit...,EX-10.58 4 d13265dex1058.htm EX-10.58\nExhibit...,EX-10.58 4 d13265dex1058.htm EX-10.58\nExhibit...,"[effective_date, jurisdiction, party, term]"

Keys list: ['effective_date', 'jurisdiction', 'party', 'term']

### 2.2 Header File

In [36]:
# read tab separated file with pandas
header = list(pd.read_csv(header_file, sep='\t').columns)
print(header)

['filename', 'keys', 'text_djvu', 'text_tesseract', 'text_textract', 'text_best']

### 2.2 Read Input Files

In [37]:
set_names = ['dev-0', 'test-A', 'train']
input_data = {}

for set_name in set_names:
    input_data[set_name] = read_input(set_name, input_path, header)
    print(f'{set_name} data shape: {input_data[set_name].shape}')

# show the dev data for verification
display(input_data['dev-0'])

dev-0 data shape: (83, 7)
test-A data shape: (203, 7)

train data shape: (254, 7)

,filename,keys,text_djvu,text_tesseract,text_textract,text_best,keys_list
0,073f3b9eb0c7088be4ef688f4edfdb6d.pdf,effective_date jurisdiction party term,EX-10 5 ex10-4 .htm EXHIBIT 10.4\nExhibit 10.4...,EX-10 5 ex10-4.htm EXHIBIT 10.4\nExhibit 10.4\...,EX-10 ex10-4.htm EXHIBIT 10.4\nExhibit 10.4\nA...,EX-10 5 ex10-4 .htm EXHIBIT 10.4\nExhibit 10.4...,"[effective_date, jurisdiction, party, term]"
1,0d3f3a02773949e285cfc3ad2fe4dbf5.pdf,effective_date jurisdiction party term,Exhibit L-2\nto Amended and Restated Loan Guar...,Exhibit I.-2\nto Amended and Restated Loan Gua...,Exhibit L-2\nto Amended and Restated Loan Guar...,Exhibit L-2\nto Amended and Restated Loan Guar...,"[effective_date, jurisdiction, party, term]"
2,0f32a3a54d9c1e42d26f66746821c3bf.pdf,effective_date jurisdiction party term,EX-99.D.3 12 d438799dex99d3.htm AMENDED AND RE...,EX-99.D.3 12 d438799dex99d3.htm AMENDED AND RE...,EX-99.D.3 12 d438799dex99d3.htm AMENDED AND RE...,EX-99.D.3 12 d438799dex99d3.htm AMENDED AND RE...,"[effective_date, jurisdiction, party, term]"
3,0fe8eaee697774ac95f9186dd2fc3364.pdf,effective_date jurisdiction party term,EX-10.1 2 a09-6413_1ex10d1.htm EX-10.1\nExhibi...,EX-10.1 2 a09-6413_1ex10d1.htm EX-10.1\nExhibi...,EX-10.1 2 a09-6413_1ex10d1.htm EX-10.1\nExhibi...,EX-10.1 2 a09-6413_1ex10d1.htm EX-10.1\nExhibi...,"[effective_date, jurisdiction, party, term]"
4,11d0a5b1f6e460c7033d57661026d00c.pdf,effective_date jurisdiction party term,EX-99.(D)(3) 8 d901048dex99d3.htm CONFIDENTIAL...,EX-99.(D)(3) 8 d901048dex99d3.htm CONFIDENTIAL...,EX-99.(D)(3) 8 d901048dex99d3.htm CONFIDENTIAL...,EX-99.(D)(3) 8 d901048dex99d3.htm CONFIDENTIAL...,"[effective_date, jurisdiction, party, term]"
...,...,...,...,...,...,...,...
78,e90afd0c36ad8ce86d62ef0cbe75cde3.pdf,effective_date jurisdiction party term,EX-99.D.3 9 d70867dex99d3.htm CONFIDENTIALITY ...,EX-99.D.3 9 d70867dex99d3.htm CONFIDENTIALITY ...,EX-99.D.3 9 d70867dex99d3.htm CONFIDENTIALITY ...,EX-99.D.3 9 d70867dex99d3.htm CONFIDENTIALITY ...,"[effective_date, jurisdiction, party, term]"
79,ead4ae70800732aeb59f689dc2e60117.pdf,effective_date jurisdiction party term,Exhibit D\nNon-Disclosure Agreement\nMicrosoft...,Exhibit D\nNon-Disclosure Agreement\nMicrosoft...,Exhibit D\nNon-Disclosure Agreement\nMicrosoft...,Exhibit D\nNon-Disclosure Agreement\nMicrosoft...,"[effective_date, jurisdiction, party, term]"
80,f28c4f3d35a152dd415f9b255122cb38.pdf,effective_date jurisdiction party term,EX-99.(E)(2) 3 dex99e2.htm CONFIDENTIALITY AGR...,EX-99.(E)(2) 3 dex99e2.htm CONFIDENTIALITY AGR...,X-99.(E)(2) 3 dex99e2.htm CONFIDENTIALITY AGRE...,EX-99.(E)(2) 3 dex99e2.htm CONFIDENTIALITY AGR...,"[effective_date, jurisdiction, party, term]"
81,f4c39490e63ee60b91f354c6b00a413b.pdf,effective_date jurisdiction party term,EX-99.(D)(3) 10 d802321dex99d3.htm EX-99.(D)(3...,EX-99.(D)(3) 10 d802321dex99d3.htm EX-99.(D)(3...,EX-99.(D)(3) 10 d802321dex99d3.htm EX-99.(D)(3...,EX-99.(D)(3) 10 d802321dex99d3.htm EX-99.(D)(3...,"[effective_date, jurisdiction, party, term]"
82,f5767a1bcfba57c7f5d07b9404a9ac3a.pdf,effective_date jurisdiction party term,EX-10.58 4 d13265dex1058.htm EX-10.58\nExhibit...,EX-10.58 4 d13265dex1058.htm EX-10.58\nExhibit...,EX-10.58 4 d13265dex1058.htm EX-10.58\nExhibit...,EX-10.58 4 d13265dex1058.htm EX-10.58\nExhibit...,"[effective_date, jurisdiction, party, term]"